name: dynamic_icon_flutter
description: A flutter plugin for dynamically changing app icon, support IOS version > 10.3 and Android
version: 0.0.8
homepage: https://github.com/chuanpham
repository: https://github.com/chuanpham/dynamic_icon_flutter
issue_tracker: https://github.com/chuanpham/dynamic_icon_flutter/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chuanpham.dynamic_icon_flutter
        pluginClass: DynamicIconFlutterPlugin
      ios:
        pluginClass: DynamicIconFlutterPlugin
